Repository sourcegraph/learn, pull requests merged in 2021-10, with the labels that each got.

#221 Add How to install Sourcegraph with Docker Compose tutorial
  posts/how-to-install-sourcegraph-with-docker-compose.md
Labels: tutorial, content

#222 Add ZeroDivisionError tutorial
  posts/how-to-troubleshoot-python-zerodivisionerror.md
Labels: tutorial, content

#224 Ltagliaferri/deved 11/hacktoberfest contributor guide
  README.md
  docs/hacktoberfest-2021.md
  posts/how-to-troubleshoot-python-zerodivisionerror.md
Labels: documentation

#220 Add videos as content type
  components/Header/index.tsx
  components/NavBar/index.tsx
  components/atoms/CollectionView/index.tsx
  components/atoms/Column/ColumnStyles.ts
  components/atoms/ContentCard/index.tsx
  components/atoms/ContentCardContainer/index.tsx
  components/atoms/ContentCardList/index.tsx
  components/templates/ArticleListTemplate/index.tsx
  components/templates/HomepageTemplate/index.tsx
  data/collections.yaml
  lib/getBaseDirectory.ts
  lib/loadRecordCollections.ts
  netlify.toml
  next.config.js
  pages/[slug].tsx
  pages/authors/[slug].tsx
  pages/index.tsx
  pages/posts/index.tsx
  pages/tags/[tag].tsx
  pages/videos/index.tsx
  videos/how-to-add-open-source-software-to-sourcegraph-cloud-video.md
  videos/how-to-add-private-code-repositories-to-sourcegraph-video.md
  videos/how-to-find-error-messages-with-sourcegraph.md
  videos/how-to-install-Sourcegraph-with-Docker-on-a-Linux-cloud-server.md
  videos/how-to-integrate-sourcegraph-into-your-workflows.md
  videos/how-to-search-commits-and-diffs-with-sourcegraph.md
  videos/how-to-use-structural-search-in-sourcegraph.md
  videos/three-ways-to-search-code-with-sourcegraph.md
  videos/what-are-diffs-in-git.md
  videos/what-are-git-branches.md
  videos/what-are-git-commits-and-how-do-they-work.md
Labels: reorg

#236 Updates to ToC positioning and homepage animations on mobile
  components/Header/HeaderStyles.ts
  components/NavBar/index.tsx
  components/atoms/TocWrapper/index.tsx
  components/templates/ArticleTemplate/index.tsx
  hooks/repositionOnScroll.ts
Labels: ready for review, styles, mobile

#337 Update tag title matching logic
  util/filterRecordsWithTag.ts
Labels: bug, ready for review

#334 Add overflow-wrap for tutorial title and body
  components/templates/ArticleTemplate/ArticleTemplateStyles.ts
  components/templates/ArticleTemplate/index.tsx
Labels: ready for review, styles

#338 Update tsconfig.json
  tsconfig.json
Labels: ready for review, tech debt

#340 Update highlighter input on Java end of file tutorial
  data/authors.yaml
  posts/how-to-troubleshoot-java-reached-end-of-file-while-parsing.md
Labels: content

#315 Create how-to-troubleshoot-python-IndexError.md
  data/authors.yaml
  posts/how-to-troubleshoot-java-reached-end-of-file-while-parsing.md
  posts/how-to-troubleshoot-python-IndexError.md
  posts/how-to-use-python-exception-chaining.md
Labels: tutorial, content, hacktoberfest-accepted
