Repository sourcegraph/learn, pull requests merged in 2021-07, with the labels that each got.

#75 Extract table of contents into side column
  components/Article.tsx
  package-lock.json
  package.json
  pages/posts/[slug].tsx
  util/serializeMdxSource.ts
Labels: Feature

#89 Add branded 404 page
  pages/404.tsx
  pages/_app.tsx
  styles/ErrorPage.scss
Labels: Feature, WIP

#91 Fix navbar, content, and footer containers
  components/Layout.tsx
Labels: bug

#105 Change meta description attribute
  components/Layout.tsx
Labels: bug

#117 Update browser title to use alternate title if it is available for SEO
  components/Article.tsx
  components/AuthorCard.tsx
  components/AuthorCardList.tsx
  posts/regular-expression-patterns.md
  util/FrontMatter.ts
  util/loadMarkdownFile.ts
Labels: ready for review

#124 Fix broken link on tutorial
  posts/three-ways-to-search-video.md
Labels: ready for review

#122 Update styles on table of contents
  components/Article.tsx
  components/TocWrapper.tsx
  styles/typography.scss
Labels: ready for review

#125 Quick ToC update to header styles
  styles/typography.scss
Labels: ready for review

#119 Add alt for header images on post index and post pages
  components/Article.tsx
  components/ContentCard.tsx
  components/ContentCardList.tsx
  pages/[slug].tsx
  posts/how-to-add-open-source-software-projects-to-sourcegraph.md
  posts/how-to-install-sourcegraph-with-docker.md
  posts/literal-search-patterns.md
  posts/regular-expression-patterns.md
  posts/three-ways-to-search-video.md
  util/FrontMatter.ts
  util/loadMarkdownFile.ts
Labels: accessibility, ready for review

#126 Update to directory structure
  netlify.toml
  next.config.js
  pages/[slug].tsx
  pages/posts/index.tsx
Labels: ready for review

#123 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#121 Omit site title suffix when using alternate title
  components/Article.tsx
  components/Layout.tsx
  components/PageLayout.tsx
  pages/404.tsx
  pages/tags/[tag].tsx
  posts/regular-expression-patterns.md
Labels: Feature, ready for review

#129 Add content type to FrontMatter and toggle logic for tag pages
  collections.yaml
  pages/tags/[tag].tsx
  posts/how-to-add-open-source-software-projects-to-sourcegraph.md
  posts/how-to-install-sourcegraph-with-docker.md
  posts/literal-search-patterns.md
  posts/regular-expression-patterns.md
  posts/three-ways-to-search-video.md
  util/FrontMatter.ts
  util/loadMarkdownFile.ts
Labels: ready for review

#128 Validate remaining FrontMatter fields
  util/loadMarkdownFile.ts
  util/validators.ts
Labels: ready for review, tech debt

#130 Validate collections yaml
  components/Article.tsx
  components/AuthorCard.tsx
  components/AuthorCardList.tsx
  components/CollectionView.tsx
  components/ContentCard.tsx
  components/Layout.tsx
  data/authors.yaml
  data/collections.yaml
  package.json
  pages/[slug].tsx
  pages/authors/index.tsx
  pages/guides/[slug].tsx
  util/AuthorCollection.ts
  util/FrontMatter.ts
  util/RecordCollection.ts
  util/RecordCollectionDefinition.ts
  util/loadAuthorCollections.ts
  util/loadCollections.ts
  util/loadMarkdownFile.ts
  util/loadRecordCollections.ts
  util/omitUndefinedFields.ts
  util/validators.ts
Labels: ready for review, tech debt

#132 Move interfaces and types to dedicated folders
  components/Article.tsx
  components/AuthorCardList.tsx
  components/CollectionView.tsx
  components/ContentCardList.tsx
  interfaces/AuthorCollection.ts
  interfaces/FrontMatter.ts
  interfaces/MarkdownFile.ts
  interfaces/RecordCollection.ts
  interfaces/RecordCollectionDefinition.ts
  pages/authors/index.tsx
  pages/index.tsx
  pages/tags/[tag].tsx
  types/MarkdownFileWithUrl.ts
  util/collectTags.ts
  util/loadAllRecords.ts
  util/loadAuthorCollections.ts
  util/loadMarkdownFile.ts
  util/loadRecordCollections.ts
  util/serializeMdxSource.ts
  util/validators.ts
Labels: ready for review, reorg

#134 Add og:type meta property
  components/Article.tsx
  components/Layout.tsx
Labels: enhancement

#133 Move document fetching to lib
  lib/listAllRecords.ts
  lib/loadAllRecords.ts
  lib/loadAuthorCollections.ts
  lib/loadMarkdownFile.ts
  lib/loadRecordCollections.ts
  lib/serializeMdxSource.ts
  pages/[slug].tsx
  pages/authors/index.tsx
  pages/guides/[slug].tsx
  pages/index.tsx
  pages/tags/[tag].tsx
Labels: reorg

#135 Component/atom/layout reorg
  components/Footer.tsx
  components/Header.tsx
  components/atoms/AuthorCard.tsx
  components/atoms/AuthorCardList.tsx
  components/atoms/CollectionView.tsx
  components/atoms/ContentCard.tsx
  components/atoms/ContentCardList.tsx
  components/atoms/CreativeCommonsNotice.tsx
  components/atoms/EmbeddedYoutubeVideo.tsx
  components/atoms/GifLikeVideo.tsx
  components/atoms/GoogleTagManager.tsx
  components/atoms/HeaderCta.tsx
  components/atoms/SourcegraphSearch.tsx
  components/atoms/TocWrapper.tsx
  components/layouts/Layout.tsx
  components/layouts/PageLayout.tsx
  components/templates/Article.tsx
  pages/404.tsx
  pages/[slug].tsx
  pages/authors/index.tsx
  pages/guides/[slug].tsx
  pages/index.tsx
  pages/tags/[tag].tsx
Labels: ready for review, reorg
