Repository sourcegraph/learn, pull requests merged in 2021-09, with the labels that each got.

#196 Add reposition hook for ToC
  components/atoms/TocWrapper/TocWrapperStyles.ts
  components/atoms/TocWrapper/index.tsx
  components/templates/ArticleTemplate/index.tsx
  hooks/highlightOnScroll.ts
  hooks/repositionOnScroll.ts
  interfaces/PositionHookObject.ts
Labels: enhancement, ready for review, styles

#187 Homepage redesign
  .eslintrc.json
  components/Footer/FooterStyles.ts
  components/Header/HeaderStyles.ts
  components/Header/index.tsx
  components/NavBar/NavBarStyles.ts
  components/NavBar/index.tsx
  components/atoms/AuthorCard/AuthorCardStyles.ts
  components/atoms/AuthorCard/index.tsx
  components/atoms/AuthorCardList/index.tsx
  components/atoms/Button/ButtonStyles.ts
  components/atoms/Card/CardStyles.ts
  components/atoms/Card/index.tsx
  components/atoms/CardLink/CardLinkStyles.ts
  components/atoms/CardLink/index.tsx
  components/atoms/Column/ColumnStyles.ts
  components/atoms/Column/index.tsx
  components/atoms/Container/ContainerStyles.ts
  components/atoms/ContentCard/ContentCardStyles.ts
  components/atoms/ContentCard/index.tsx
  components/atoms/ContentCardContainer/ContentCardContainerStyles.ts
  components/atoms/ContentCardContainer/index.tsx
  components/atoms/ContentCardList/index.tsx
  components/atoms/HeaderCta/HeaderCtaStyles.ts
  components/atoms/HeaderCta/index.tsx
  components/atoms/SourcegraphSearch/index.tsx
  components/atoms/TocWrapper/TocWrapperStyles.ts
  components/atoms/TocWrapper/index.tsx
  components/layouts/PageLayout.tsx
  components/templates/ArticleTemplate/index.tsx
  components/templates/HomepageTemplate/index.tsx
  components/templates/TagTemplate/index.tsx
  hooks/highlightOnScroll.ts
  hooks/repositionOnScroll.ts
  interfaces/PositionHookObject.ts
  pages/[slug].tsx
  pages/index.tsx
  pages/tags/[tag].tsx
  util/validators.ts
Labels: enhancement, ready for review, reorg, styles

#197 Add dates
  README.md
  components/atoms/EmbeddedYoutubeVideo/index.tsx
  components/templates/ArticleTemplate/ArticleTemplateStyles.ts
  components/templates/ArticleTemplate/index.tsx
  interfaces/FrontMatter.ts
  pages/[slug].tsx
  posts/how-to-add-open-source-software-projects-to-sourcegraph-cloud.md
  posts/how-to-add-open-source-software-to-sourcegraph-cloud-video.md
  posts/how-to-add-private-code-repositories-to-sourcegraph-video.md
  posts/how-to-add-private-code-repositories-to-sourcegraph.md
  posts/how-to-find-error-messages-with-sourcegraph.md
  posts/how-to-install-Sourcegraph-with-Docker-on-a-Linux-cloud-server.md
  posts/how-to-install-sourcegraph-on-linux-with-docker.md
  posts/how-to-install-sourcegraph-on-mac-with-docker.md
  posts/how-to-install-sourcegraph-on-windows-with-docker.md
  posts/how-to-integrate-sourcegraph-into-your-workflows.md
  posts/how-to-search-code-with-sourcegraph-a-cheat-sheet.md
  posts/how-to-search-code-with-sourcegraph-using-literal-patterns.md
  posts/how-to-search-with-sourcegraph-using-regular-expression-patterns.md
  posts/how-to-search-with-sourcegraph-using-structural-patterns.md
  posts/three-ways-to-search-code-with-sourcegraph.md
  util/validators.ts
Labels: feature, ready for review

#201 Update dependencies
  package-lock.json
  package.json
Labels: npm, ready for review, tech debt

#203 Update rehype-react and sass
  package-lock.json
  package.json
Labels: npm, tech debt

#202 Add How to create a Sourcegraph cloud account tutorial
  posts/how-to-create-a-sourcegraph-cloud-account.md
Labels: tutorial, content

#200 Add content: How to commit code with the Git CLI
  posts/how-to-commit-code-with-the-git-command-line-interface.md
Labels: ready for review, tutorial, content

#199 Add content: How to commit code to a Git repository with VS Code
  posts/how-to-commit-code-to-a-git-repository-with-visual-studio-code.md
Labels: ready for review, tutorial, content

#205 Add "How to create a self-hosted Sourcegraph account" tutorial
  posts/how-to-create-a-self-hosted-sourcegraph-account.md
  posts/how-to-create-a-sourcegraph-cloud-account.md
Labels: tutorial, content

#204 Add content: How to commit code to a Git repository with GitHub Desktop
  posts/how-to-commit-code-to-a-git-repository-with-github-desktop.md
Labels: ready for review, tutorial, content

#214 Add author profiles
  components/atoms/AuthorCard/AuthorCardStyles.ts
  components/atoms/AuthorCard/index.tsx
  components/atoms/AuthorCardList/AuthorCardListStyles.ts
  components/atoms/AuthorCardList/index.tsx
  components/templates/ArticleTemplate/ArticleTemplateStyles.ts
  components/templates/ArticleTemplate/index.tsx
  components/templates/AuthorTemplate/AuthorTemplateStyles.ts
  components/templates/AuthorTemplate/index.tsx
  data/authors.yaml
  interfaces/AuthorCollection.ts
  pages/[slug].tsx
  pages/authors/[slug].tsx
  pages/authors/index.tsx
  util/validators.ts
Labels: feature, ready for review

#216 Add user testing article, update authors.yaml
  data/authors.yaml
  posts/how-to-user-test-software-projects-usability-tests.md
Labels: tutorial, content

#206 Add content: How to stage and unstage files in Git
  posts/how-to-stage-and-unstage-files-in-git.md
Labels: ready for review, tutorial, content

#213 Remove description from frontend, keep as meta
  components/atoms/CollectionView/index.tsx
  components/atoms/ContentCard/ContentCardStyles.ts
  components/atoms/ContentCard/index.tsx
  components/atoms/ContentCardContainer/index.tsx
  components/atoms/ContentCardList/index.tsx
  interfaces/FrontMatter.ts
Labels: enhancement, ready for review, styles

#208 Add content: What are commits and how do they work?
  posts/what-are-git-commits-and-how-do-they-work.md
Labels: ready for review, content, video

#209 Add content: What are branches?
  posts/what-are-git-branches.md
Labels: ready for review, content, video

#210 Add content: How to search commits and diffs with Sourcegraph
  posts/how-to-search-commits-and-diffs-with-sourcegraph.md
Labels: ready for review, content, video

#217 Add Python type hinting tutorial
  posts/getting-started-with-type-hinting-in-python.md
Labels: tutorial, content

#218 Updates to footer
  components/Footer/FooterStyles.ts
  components/Footer/index.tsx
  components/atoms/Column/ColumnStyles.ts
Labels: enhancement

#211 Add content: What are diffs?
  posts/what-are-diffs-in-git.md
Labels: ready for review, content, video

#212 Add content: How to use structural search in Sourcegraph
  posts/how-to-use-structural-search-in-sourcegraph.md
Labels: ready for review, content, video

#219 Meta tag rewrite & add author meta tags
  components/layouts/Layout.tsx
  components/layouts/PageLayout.tsx
  components/templates/ArticleTemplate/index.tsx
  components/templates/AuthorTemplate/index.tsx
  components/templates/HomepageTemplate/index.tsx
  components/templates/TagTemplate/index.tsx
  interfaces/FrontMatter.ts
  interfaces/MetaTags.ts
  lib/metaDataDefaults.ts
  pages/404.tsx
  pages/[slug].tsx
  pages/tags/[tag].tsx
  posts/getting-started-with-type-hinting-in-python.md
  posts/how-to-add-open-source-software-to-sourcegraph-cloud-video.md
  posts/how-to-add-private-code-repositories-to-sourcegraph-video.md
  posts/how-to-add-private-code-repositories-to-sourcegraph.md
  posts/how-to-create-a-self-hosted-sourcegraph-account.md
  posts/how-to-create-a-sourcegraph-cloud-account.md
  posts/how-to-find-error-messages-with-sourcegraph.md
  posts/how-to-install-Sourcegraph-with-Docker-on-a-Linux-cloud-server.md
  posts/how-to-install-sourcegraph-on-linux-with-docker.md
  posts/how-to-install-sourcegraph-on-mac-with-docker.md
  posts/how-to-install-sourcegraph-on-windows-with-docker.md
  posts/how-to-integrate-sourcegraph-into-your-workflows.md
  posts/how-to-search-code-with-sourcegraph-a-cheat-sheet.md
  posts/how-to-search-code-with-sourcegraph-using-literal-patterns.md
  posts/how-to-search-with-sourcegraph-using-regular-expression-patterns.md
  posts/how-to-search-with-sourcegraph-using-structural-patterns.md
  posts/how-to-user-test-software-projects-usability-tests.md
  posts/three-ways-to-search-code-with-sourcegraph.md
  util/collectTags.ts
  util/validators.ts
Labels: enhancement, ready for review, tech debt, reorg
