Repository sourcegraph/learn, pull requests merged in 2021-11, with the labels that each got.

#329 Record index page redesign plus load more records functionality
  components/Header/HeaderStyles.ts
  components/Header/index.tsx
  components/atoms/Button/index.tsx
  components/atoms/Card/CardStyles.ts
  components/atoms/CardLink/CardLinkStyles.ts
  components/atoms/Column/ColumnStyles.ts
  components/templates/RecordIndexTemplate/index.tsx
  components/templates/TagTemplate/index.tsx
  hooks/loadMore.ts
  interfaces/LoadMoreHookObject.ts
  pages/posts/index.tsx
  pages/tags/[tag].tsx
  pages/videos/index.tsx
Labels: enhancement, feature, ready for review

#354 Batch update dependencies
  package-lock.json
  package.json
Labels: npm, ready for review, tech debt

#355 Get ESLint running again
  interfaces/FrontMatter.ts
  package-lock.json
  package.json
Labels: bug, ready for review

#356 Upgrade to Next.js 12
  .eslintrc.json
  .gitignore
  components/atoms/GoogleTagManager/index.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  tsconfig.json
Labels: npm, ready for review

#361 Pin eslint-plugin-unicorn
  package-lock.json
  package.json
Labels: bug, npm, ready for review

#357 Create how-to-troubleshoot-java-NegativeArraySizeException.md
  posts/how-to-troubleshoot-java-NegativeArraySizeException.md
Labels: tutorial, content

#341 Update `Highlighter` instructions in README
  README.md
Labels: documentation, ready for review

#366 Update width on center column
  components/atoms/Column/ColumnStyles.ts
  components/atoms/TocWrapper/TocWrapperStyles.ts
Labels: ready for review, styles

#359 Title casing of product name
  posts/how-to-add-open-source-software-projects-to-sourcegraph-cloud.md
  posts/how-to-add-private-code-repositories-to-sourcegraph.md
  posts/how-to-create-a-sourcegraph-cloud-account.md
  posts/how-to-install-sourcegraph-on-linux-with-docker.md
  posts/how-to-install-sourcegraph-on-mac-with-docker.md
  posts/how-to-install-sourcegraph-on-windows-with-docker.md
  posts/how-to-install-sourcegraph-with-docker-compose.md
  posts/how-to-search-code-with-sourcegraph-a-cheat-sheet.md
  posts/how-to-stage-and-unstage-files-in-git.md
  videos/how-to-add-open-source-software-to-sourcegraph-cloud-video.md
  videos/how-to-add-private-code-repositories-to-sourcegraph-video.md
  videos/how-to-find-error-messages-with-sourcegraph.md
  videos/how-to-install-Sourcegraph-with-Docker-on-a-Linux-cloud-server.md
Labels: content

#370 Add how to set up a TS programming environment tutorial
  data/authors.yaml
  posts/how-to-set-up-a-typescript-programming-environment.md
Labels: tutorial, content

#368 Tag page redesign
  components/atoms/CardLink/CardLinkStyles.ts
  components/atoms/CardLink/index.tsx
  components/atoms/ContentCard/index.tsx
  components/atoms/ContentCardList/index.tsx
  components/atoms/FeaturedContentBlock/FeaturedContentBlockStyles.ts
  components/atoms/FeaturedContentBlock/index.tsx
  components/atoms/RecordList/RecordListStyles.ts
  components/atoms/RecordList/index.tsx
  components/atoms/RecordListTab/RecordListTabStyles.ts
  components/atoms/RecordListTab/index.tsx
  components/atoms/SideBarRecordList/SideBarRecordListStyles.ts
  components/atoms/SideBarRecordList/index.tsx
  components/templates/RecordIndexTemplate/index.tsx
  components/templates/TagTemplate/index.tsx
  hooks/loadMore.ts
  interfaces/LoadMoreHookObject.ts
  pages/posts/index.tsx
  pages/tags/[tag].tsx
  pages/videos/index.tsx
  posts/how-to-commit-code-to-a-git-repository-with-github-desktop.md
  util/filterRecordsWithTag.ts
  util/markdownWithUrls.ts
  util/showMoreButton.ts
Labels: feature, ready for review

#365 Add dark mode
  .eslintrc.json
  components/Footer/FooterStyles.ts
  components/Footer/index.tsx
  components/Header/HeaderStyles.ts
  components/Header/index.tsx
  components/NavBar/NavBarStyles.ts
  components/NavBar/index.tsx
  components/atoms/Button/ButtonStyles.ts
  components/atoms/Button/index.tsx
  components/atoms/Card/CardStyles.ts
  components/atoms/CardLink/CardLinkStyles.ts
  components/atoms/CollectionView/CollectionViewStyles.ts
  components/atoms/ContentCard/ContentCardStyles.ts
  components/atoms/ContentCard/index.tsx
  components/atoms/CreativeCommonsNotice/CreativeCommonsNoticeStyles.ts
  components/atoms/RecordList/RecordListStyles.ts
  components/atoms/RecordList/index.tsx
  components/atoms/RecordListTab/RecordListTabStyles.ts
  components/atoms/RecordListTab/index.tsx
  components/atoms/SiteSearchBar/SiteSearchBarStyles.ts
  components/atoms/SourcegraphSearch/SourcegraphSearchStyles.ts
  components/atoms/SourcegraphSearch/index.tsx
  components/atoms/TocWrapper/TocWrapperStyles.ts
  components/templates/ArticleTemplate/ArticleTemplateStyles.ts
  components/templates/ArticleTemplate/index.tsx
  components/templates/AuthorTemplate/AuthorTemplateStyles.ts
  components/templates/HomepageTemplate/index.tsx
  components/templates/RecordIndexTemplate/index.tsx
  components/templates/TagTemplate/index.tsx
  components/themes/colors.ts
  components/themes/theme.tsx
  hooks/contexts/theme.ts
  hooks/darkMode.ts
  interfaces/Colors.ts
  interfaces/DarkModeHookObject.ts
  lib/serializeMdxSource.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/tags/[tag].tsx
  styles/styles.scss
Labels: feature, ready for review, styles

#376 Add intro to types in TS tutorial
  posts/introduction-to-types-in-typescript.md
Labels: tutorial, content

#374 Add hover styles on links in tutorial body
  components/templates/ArticleTemplate/ArticleTemplateStyles.ts
Labels: ready for review, styles

#375 404 page update
  components/templates/ErrorTemplate/ErrorTemplateStyles.ts
  components/templates/ErrorTemplate/index.tsx
Labels: enhancement, ready for review

#373 Highlighter Updates
  README.md
  components/atoms/Highlighter/HighlighterStyles.ts
  components/atoms/Highlighter/index.tsx
  components/atoms/OutputHighlighter/OutputHighlighterStyles.ts
  components/atoms/OutputHighlighter/index.tsx
  components/atoms/PrismSyntaxHighlighter/PrismSyntaxHighlighterStyles.ts
  components/atoms/PrismSyntaxHighlighter/index.tsx
  components/templates/ArticleTemplate/ArticleTemplateStyles.ts
  components/templates/ArticleTemplate/index.tsx
  posts/getting-started-with-type-hinting-in-python.md
  posts/how-to-commit-code-to-a-git-repository-with-github-desktop.md
  posts/how-to-commit-code-to-a-git-repository-with-visual-studio-code.md
  posts/how-to-commit-code-with-the-git-command-line-interface.md
  posts/how-to-create-a-self-hosted-sourcegraph-account.md
  posts/how-to-distribute-a-podcast-using-an-rss-feed.md
  posts/how-to-install-sourcegraph-on-linux-with-docker.md
  posts/how-to-install-sourcegraph-on-mac-with-docker.md
  posts/how-to-install-sourcegraph-on-windows-with-docker.md
  posts/how-to-install-sourcegraph-with-docker-compose.md
  posts/how-to-search-with-sourcegraph-using-structural-patterns.md
  posts/how-to-set-up-a-typescript-programming-environment.md
  posts/how-to-stage-and-unstage-files-in-git.md
  posts/how-to-troubleshoot-JavaScript-SyntaxError-missing-}-after-function-body.md
  posts/how-to-troubleshoot-arrayindexoutofboundsexception.md
  posts/how-to-troubleshoot-java-NegativeArraySizeException.md
  posts/how-to-troubleshoot-java-class-not-found-exception.md
  posts/how-to-troubleshoot-java-error-class-is-public-should-be-declared-in-its-own-file.md
  posts/how-to-troubleshoot-java-nullpointerexception.md
  posts/how-to-troubleshoot-java-outofmemoryexception.md
  posts/how-to-troubleshoot-java-reached-end-of-file-while-parsing.md
  posts/how-to-troubleshoot-java-stackoverflowerror.md
  posts/how-to-troubleshoot-java-stringindexoutofboundsexception.md
  posts/how-to-troubleshoot-javascript-error-enospc-write.md
  posts/how-to-troubleshoot-javascript-internalerror-too-much-recursion.md
  posts/how-to-troubleshoot-javascript-json-parse.md
  posts/how-to-troubleshoot-javascript-null-has-no-properties.md
  posts/how-to-troubleshoot-javascript-permission-denied-to-access-property-x.md
  posts/how-to-troubleshoot-js-syntax-error-missing-variable-name.md
  posts/how-to-troubleshoot-linux-error-no-such-file-or-directory.md
  posts/how-to-troubleshoot-linux-not-a-dir.md
  posts/how-to-troubleshoot-linux-permission-denied.md
  posts/how-to-troubleshoot-php-syntax-error-unexpected-end-of-file.md
  posts/how-to-troubleshoot-python-IndexError.md
  posts/how-to-troubleshoot-python-max-recursion-depth-exceeded.md
  posts/how-to-troubleshoot-python-nameerror.md
  posts/how-to-troubleshoot-python-os-error.md
  posts/how-to-troubleshoot-python-zerodivisionerror.md
  posts/how-to-use-python-exception-chaining.md
  posts/how-to-use-the-git-status-command-to-understand-the-state-of-a-git-repository.md
  util/returnHighlightIndices.ts
  videos/how-to-install-Sourcegraph-with-Docker-on-a-Linux-cloud-server.md
Labels: bug, enhancement, ready for review

#330 Tutorial: add Python AttributeError to tutorials
  data/authors.yaml
  posts/how-to-troubleshoot-python-attributeerror.md
Labels: tutorial, content, hacktoberfest-accepted

#378 Add Sourcegraph Cloud tag
  posts/how-to-add-open-source-software-projects-to-sourcegraph-cloud.md
  posts/how-to-add-private-code-repositories-to-sourcegraph.md
  posts/how-to-create-a-sourcegraph-cloud-account.md
  posts/how-to-search-code-with-sourcegraph-a-cheat-sheet.md
  posts/how-to-search-code-with-sourcegraph-using-literal-patterns.md
  posts/how-to-search-with-sourcegraph-using-regular-expression-patterns.md
  posts/how-to-search-with-sourcegraph-using-structural-patterns.md
  videos/how-to-add-open-source-software-to-sourcegraph-cloud-video.md
  videos/how-to-add-private-code-repositories-to-sourcegraph-video.md
  videos/how-to-find-error-messages-with-sourcegraph.md
  videos/how-to-install-Sourcegraph-with-Docker-on-a-Linux-cloud-server.md
  videos/how-to-integrate-sourcegraph-into-your-workflows.md
  videos/how-to-search-commits-and-diffs-with-sourcegraph.md
  videos/how-to-use-structural-search-in-sourcegraph.md
  videos/three-ways-to-search-code-with-sourcegraph.md
Labels: bug, content

#379 Add Learning React concepts with Sourcegraph tutorial
  data/authors.yaml
  posts/learning-react-concepts-with-sourcegraph.md
Labels: tutorial, content

#380 Copyedit
  posts/learning-react-concepts-with-sourcegraph.md
Labels: content

#377 Add local cache for data
  .gitignore
  components/atoms/RecordList/index.tsx
  components/templates/RecordIndexTemplate/index.tsx
  components/templates/TagTemplate/index.tsx
  hooks/loadMore.ts
  interfaces/FilteredRecords.ts
  interfaces/MarkdownFileWithUrl.ts
  interfaces/PageData.ts
  lib/api/fetchPageData.ts
  lib/api/getPageData.ts
  lib/loadAllRecords.ts
  lib/loadMarkdownFile.ts
  lib/loadRecordCollections.ts
  netlify.toml
  next.config.js
  package.json
  pages/[slug].tsx
  pages/authors/[slug].tsx
  pages/index.tsx
  pages/posts/index.tsx
  pages/tags/[tag].tsx
  pages/videos/index.tsx
  script/install.sh
  script/runBuild.sh
  script/runDev.sh
  util/collectTags.ts
  util/filterRecordsWithTag.ts
  util/showMoreButton.ts
Labels: ready for review, performance, optimization

#382 Series dropdown menu
  components/atoms/CollectionView/CollectionViewStyles.ts
  components/atoms/CollectionView/index.tsx
  components/atoms/Column/ColumnStyles.ts
  components/atoms/TocWrapper/TocWrapperStyles.ts
  components/layouts/PageLayout.tsx
  components/templates/ArticleTemplate/index.tsx
Labels: enhancement, feature, ready for review

#300 Added file "how-to-troubleshoot-java-outofmemoryexception.md" for review
  data/authors.yaml
Labels: tutorial, content, hacktoberfest-accepted

#331 Create Python_Troubleshooting_Tutorial_KeyError.md
  posts/how-to-troubleshoot-python-keyerror.md
Labels: tutorial, content, hacktoberfest-accepted

#332 feat: add troubleshoot for python ValueError
  posts/how-to-troubleshoot-python-invalid-literal-for-int.md
Labels: tutorial, content, hacktoberfest-accepted

#333 feat: added a import error tutorial for Python
  posts/how-to-troubleshoot-python-import-error.md
Labels: tutorial, content, hacktoberfest-accepted

#342 added invalid code point tutorial closes #238
  data/authors.yaml
  posts/how-to-troubleshoot-javascript-invalidcodepoint.md
Labels: tutorial, content, hacktoberfest-accepted

#367 feat: Add troubleshooting tutorial for Python IndentationError
  data/authors.yaml
  posts/how-to-troubleshoot-python-intendation-error.md
Labels: tutorial, content

#383 Small edits
  posts/how-to-stage-and-unstage-files-in-git.md
  posts/how-to-troubleshoot-javascript-invalidcodepoint.md
  posts/how-to-troubleshoot-python-import-error.md
  posts/how-to-troubleshoot-python-invalid-literal-for-int.md
  videos/how-to-integrate-sourcegraph-into-your-workflows.md
  videos/how-to-search-commits-and-diffs-with-sourcegraph.md
Labels: bug, wait to merge, content

#384 Add right padding for code elements in Highlighter
  components/atoms/Highlighter/HighlighterStyles.ts
Labels: bug, ready for review, styles

#385 Fix height on homepage cards
  components/atoms/ContentCard/ContentCardStyles.ts
Labels: bug, ready for review, styles
