Repository sourcegraph/learn, pull requests merged in 2021-12, with the labels that each got.

#389 Add how to wireframe tutorial
  posts/how-to-wireframe-a-software-product.md
Labels: tutorial, content

#369 Add "How to make a composer package" tutorial
  posts/how-to-make-a-composer-package.md
Labels: tutorial, content

#390 Micro git add tutorials
  posts/how-to-rename-or-remove-a-file-in-git.md
  posts/how-to-reset-a-git-repository.md
  posts/how-to-restore-a-change-in-git.md
  posts/how-to-stage-all-changes-in-git.md
  posts/how-to-stage-an-empty-directory-in-git.md
  posts/how-to-stage-directories-in-git.md
  posts/how-to-stage-files-in-git.md
  posts/how-to-stage-the-deletion-of-a-file-in-git.md
  posts/how-to-stage-to-git-using-a-glob-pattern.md
Labels: tutorial, content

#387 Add next in series link
  components/atoms/CollectionLink/CollectionLinkStyles.ts
  components/atoms/CollectionLink/index.tsx
  components/templates/ArticleTemplate/index.tsx
Labels: feature

#405 Update README with addition about backslashes
  README.md
Labels: documentation, ready for review

#407 Create how-to-create-user-flow-diagrams-for-software-products.md
  posts/how-to-create-user-flow-diagrams-for-software-products.md
Labels: tutorial, content

#406 Linting updates
  package-lock.json
  package.json
Labels: npm, ready for review

#415 Add UX tutorials
  posts/how-to-conduct-a-user-interview-as-part-of-software-product-development.md
  posts/how-to-create-a-self-hosted-sourcegraph-account.md
  posts/how-to-create-a-sourcegraph-cloud-account.md
  posts/how-to-create-and-use-personas-of-target-users.md
  posts/how-to-create-user-journey-maps-for-software-products.md
  posts/how-to-install-sourcegraph-with-docker-compose.md
  posts/how-to-user-test-software-projects-usability-tests.md
Labels: tutorial, content

#416 Fix logo issue
  components/NavBar/NavBarStyles.ts
Labels: bug, styles

#417 Adjust sizing on card links
  components/atoms/CardLink/CardLinkStyles.ts
  components/atoms/FeaturedContentBlock/FeaturedContentBlockStyles.ts
Labels: bug, styles

#418 Update remark-rehype and next
  package-lock.json
  package.json
Labels: tech debt

#420 Add regex Java tutorial
  posts/getting-started-with-type-hinting-in-python.md
  posts/how-to-add-open-source-software-projects-to-sourcegraph-cloud.md
  posts/how-to-add-private-code-repositories-to-sourcegraph.md
  posts/how-to-create-a-self-hosted-sourcegraph-account.md
  posts/how-to-search-code-with-sourcegraph-a-cheat-sheet.md
  posts/how-to-search-code-with-sourcegraph-using-literal-patterns.md
  posts/how-to-search-with-sourcegraph-using-regular-expression-patterns.md
  posts/regular-expressions-in-java.md
Labels: tutorial, content

#421 Add Python installation guide for Windows
  posts/how-to-install-and-set-up-python-on-windows.md
  posts/how-to-install-sourcegraph-on-windows-with-docker.md
Labels: tutorial, content

#422 Update banner images
  posts/how-to-create-and-use-personas-of-target-users.md
  posts/how-to-install-and-set-up-python-on-windows.md
  posts/how-to-reset-a-git-repository.md
  posts/how-to-troubleshoot-JavaScript-SyntaxError-missing-}-after-function-body.md
  posts/how-to-troubleshoot-arrayindexoutofboundsexception.md
  posts/how-to-troubleshoot-java-NegativeArraySizeException.md
  posts/how-to-troubleshoot-java-class-not-found-exception.md
  posts/how-to-troubleshoot-java-error-class-is-public-should-be-declared-in-its-own-file.md
  posts/how-to-troubleshoot-java-nullpointerexception.md
  posts/how-to-troubleshoot-java-outofmemoryexception.md
  posts/how-to-troubleshoot-java-reached-end-of-file-while-parsing.md
  posts/how-to-troubleshoot-java-stackoverflowerror.md
  posts/how-to-troubleshoot-java-stringindexoutofboundsexception.md
  posts/how-to-troubleshoot-javascript-TypeError-invalid-assignment-to-const-x.md
  posts/how-to-troubleshoot-javascript-error-enospc-write.md
  posts/how-to-troubleshoot-javascript-internalerror-too-much-recursion.md
  posts/how-to-troubleshoot-javascript-invalidcodepoint.md
  posts/how-to-troubleshoot-javascript-json-parse.md
  posts/how-to-troubleshoot-javascript-null-has-no-properties.md
  posts/how-to-troubleshoot-javascript-permission-denied-to-access-property-x.md
  posts/how-to-troubleshoot-js-syntax-error-missing-variable-name.md
  posts/how-to-troubleshoot-linux-error-no-such-file-or-directory.md
  posts/how-to-troubleshoot-linux-not-a-dir.md
  posts/how-to-troubleshoot-linux-permission-denied.md
  posts/how-to-troubleshoot-php-syntax-error-unexpected-end-of-file.md
  posts/how-to-troubleshoot-python-IndexError.md
  posts/how-to-troubleshoot-python-attributeerror.md
  posts/how-to-troubleshoot-python-import-error.md
  posts/how-to-troubleshoot-python-intendation-error.md
  posts/how-to-troubleshoot-python-invalid-literal-for-int.md
  posts/how-to-troubleshoot-python-keyerror.md
  posts/how-to-troubleshoot-python-max-recursion-depth-exceeded.md
  posts/how-to-troubleshoot-python-nameerror.md
  posts/how-to-troubleshoot-python-os-error.md
  posts/how-to-use-python-exception-chaining.md
Labels: content
