Repository sourcegraph/learn, pull requests merged in 2021-08, with the labels that each got.

#156 Use module path aliases for imports
  components/Footer/index.tsx
  components/Header/index.tsx
  components/NavBar/index.tsx
  components/atoms/AuthorCard/index.tsx
  components/atoms/AuthorCardList/index.tsx
  components/atoms/CollectionView/index.tsx
  components/atoms/ContentCard/index.tsx
  components/atoms/ContentCardList/index.tsx
  components/atoms/CreativeCommonsNotice/index.tsx
  components/atoms/SourcegraphSearch/index.tsx
  components/layouts/Layout.tsx
  components/layouts/PageLayout.tsx
  components/templates/ArticleTemplate/index.tsx
  interfaces/MarkdownFile.ts
  interfaces/MarkdownFileWithUrl.ts
  interfaces/RecordCollection.ts
  lib/loadAllRecords.ts
  lib/loadAuthorCollections.ts
  lib/loadMarkdownFile.ts
  lib/loadRecordCollections.ts
  lib/serializeMdxSource.ts
  pages/404.tsx
  pages/[slug].tsx
  pages/_app.tsx
  pages/authors/index.tsx
  pages/guides/[slug].tsx
  pages/index.tsx
  pages/tags/[tag].tsx
  tsconfig.json
  types/MarkdownFileWithUrl.ts
  util/collectTags.ts
  util/validators.ts
Labels: ready for review, reorg

#157 Use brand colors in components
  components/Footer/FooterStyles.ts
  components/atoms/Button/ButtonStyles.ts
  components/atoms/CollectionView/CollectionViewStyles.ts
  components/atoms/TocWrapper/TocWrapperStyles.ts
  components/templates/ArticleTemplate/ArticleTemplateStyles.ts
Labels: ready for review, styles

#159 Add content: How to Find Error Messages with Sourcegraph (Video)
  posts/how-to-find-error-messages-with-sourcegraph.md
  posts/three-ways-to-search-video.md
  public/headers/how-to-find-error-messages-with-sourcegraph-thumbnail.jpg
  public/headers/three-ways-to-search-thumbnail.jpg
Labels: ready for review, content

#160 Add bundle analyzer and update React imports
  .eslintrc.json
  components/Footer/index.tsx
  components/Header/index.tsx
  components/NavBar/index.tsx
  components/atoms/AuthorCard/index.tsx
  components/atoms/AuthorCardList/index.tsx
  components/atoms/Button/index.tsx
  components/atoms/Card/index.tsx
  components/atoms/CollectionView/index.tsx
  components/atoms/Column/index.tsx
  components/atoms/Container/index.tsx
  components/atoms/ContentCard/index.tsx
  components/atoms/ContentCardList/index.tsx
  components/atoms/CreativeCommonsNotice/index.tsx
  components/atoms/EmbeddedYoutubeVideo/index.tsx
  components/atoms/GifLikeVideo/index.tsx
  components/atoms/GoogleTagManager/index.tsx
  components/atoms/HeaderCta/index.tsx
  components/atoms/Row/index.tsx
  components/atoms/SourcegraphSearch/index.tsx
  components/atoms/TocWrapper/index.tsx
  components/layouts/Layout.tsx
  components/layouts/PageLayout.tsx
  components/templates/ArticleTemplate/index.tsx
  components/templates/ErrorTemplate/index.tsx
  next.config.js
  package-lock.json
  package.json
  pages/404.tsx
  pages/[slug].tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/authors/index.tsx
  pages/index.tsx
  pages/tags/[tag].tsx
Labels: enhancement, ready for review

#163 Remove package dependencies for ToC render
  components/atoms/TocWrapper/TocWrapperStyles.ts
  components/atoms/TocWrapper/index.tsx
  components/templates/ArticleTemplate/index.tsx
  lib/serializeMdxSource.ts
  package-lock.json
  package.json
  pages/[slug].tsx
  util/createRandomId.ts
  util/returnHeaders.ts
  util/sluggify.ts
  util/sluggifyHeaders.ts
Labels: ready for review, tech debt

#164 Update YT video ID for reuploaded "How to find error messages" video
  posts/how-to-find-error-messages-with-sourcegraph.md
Labels: ready for review, content, video

#162 Add content: How To Search with Sourcegraph using Structural Patterns
  components/templates/ArticleTemplate/index.tsx
  data/collections.yaml
  posts/regular-expression-patterns.md
  posts/structural-search-patterns.md
  public/tutorial-images/enable-structural-search.mp4
Labels: ready for review, tutorial

#165 Remove globby
  lib/listAllRecords.ts
  package-lock.json
  package.json
  pages/authors/index.tsx
  pages/guides/[slug].tsx
  pages/tags/[tag].tsx
Labels: npm, ready for review, tech debt

#167 SourcegraphSearch input styles update
  components/atoms/SourcegraphSearch/SourcegraphSearchStyles.ts
  components/atoms/SourcegraphSearch/index.tsx
Labels: ready for review, styles

#168 Update dependencies
  package-lock.json
  package.json
Labels: npm, ready for review, tech debt

#169 Use env vars and add install script
  .gitignore
  README.md
  components/atoms/GoogleTagManager/index.tsx
  components/layouts/Layout.tsx
  netlify.toml
  next.config.js
  script/install.sh
  site-config.ts
Labels: documentation, ready for review, infrastructure

#170 Bump to Next.js 11
  next-env.d.ts
  next.config.js
  package-lock.json
  package.json
Labels: npm, ready for review

#171 Add tutorial
  posts/how-to-add-private-code-repositories-to-sourcegraph.md
  public/headers/how-to-find-error-messages-with-sourcegraph-thumbnail.jpg
  public/tutorial-images/sourcegraph-list-of-saved-repos.png
  public/tutorial-images/sourcegraph-repo-list-private-label.png
  public/tutorial-images/sourcegraph-repositories-section.png
  public/tutorial-images/sourcegraph-sync-selected-repos.png
  public/tutorial-images/sourcegraph-visibility-private-code-search.png
Labels: tutorial

#172 Completes DEVED-100. Sourcegraph's cheat sheet
  data/authors.yaml
  posts/sourcegraph-cheat-sheet.md
Labels: tutorial

#173 Fix width on card images
  components/atoms/ContentCard/ContentCardStyles.ts
  components/atoms/ContentCard/index.tsx
Labels: bug

#174 Update nested header styles on ToC
  components/atoms/TocWrapper/TocWrapperStyles.ts
  components/atoms/TocWrapper/index.tsx
  interfaces/TocHeader.ts
  util/convertHeaders.ts
  util/returnHeaders.ts
  util/returnNestedHeaders.ts
Labels: enhancement, ready for review, styles

#175 Add video: How to add private code on Sourcegraph cloud
  posts/how-to-add-private-code-repositories-to-sourcegraph-video.md
  public/headers/how-to-add-private-code-to-sourcegraph-thumbnail.jpg
Labels: ready for review, content, video

#176 Removing forestry CMS
  .forestry/front_matter/templates/post.yml
  .forestry/settings.yml
Labels: tech debt

#184 Add content: How to integrate Sourcegraph into your workflows
  posts/how-to-integrate-sourcegraph-into-your-workflows.md
Labels: ready for review, content, video

#188 Update ToC on larger screens
  components/atoms/TocWrapper/TocWrapperStyles.ts
Labels: styles

#189 Add redirects for changed posts
  netlify.toml
Labels: bug, ready for review

#186 Add two Sourcegraph videos
  components/atoms/TocWrapper/TocWrapperStyles.ts
  components/layouts/Layout.tsx
  posts/how-to-add-open-source-software-to-sourcegraph-cloud-video.md
  posts/how-to-install-Sourcegraph-with-Docker-on-a-Linux-cloud-server.md
  posts/how-to-install-sourcegraph-on-linux-with-docker.md
  posts/how-to-install-sourcegraph-on-mac-with-docker.md
  posts/how-to-install-sourcegraph-on-windows-with-docker.md
  posts/three-ways-to-search-code-with-sourcegraph.md
Labels: WIP, content, video
