Repository sourcegraph/learn, pull requests merged in 2022-01, with the labels that each got.

#434 Update code blocks with highlighting
  posts/how-to-search-code-with-sourcegraph-a-cheat-sheet.md
  posts/how-to-troubleshoot-arrayindexoutofboundsexception.md
  posts/how-to-use-python-exception-chaining.md
  posts/learning-react-concepts-with-sourcegraph.md
Labels: bug, content

#435 Add more social links — GitHub and Twitch
  components/templates/AuthorTemplate/index.tsx
  data/authors.yaml
  interfaces/AuthorCollection.ts
  util/validators.ts
Labels: enhancement

#438 Add Java Map tutorial, update TS
  package-lock.json
  package.json
  posts/how-to-use-the-different-map-variants-of-java.md
Labels: npm, content

#443 Add history of code search tutorial
  posts/a-short-history-of-code-search.md
Labels: content

#444 Reorganize docs
  README.md
  docs/content.md
  docs/development.md
Labels: documentation

#442 Style updates for featured content blocks on tag pages
  components/atoms/CardLink/CardLinkStyles.ts
  components/atoms/ContentCard/ContentCardStyles.ts
  components/atoms/FeaturedContentBlock/FeaturedContentBlockStyles.ts
  next-env.d.ts
  package-lock.json
  package.json
Labels: ready for review, styles
